import { createSignal, onCleanup } from 'solid-js'
import { authStore } from '../stores/authStore'
import {
  getMyAdventuresById,
  postMyAdventures,
  putMyAdventuresById,
} from '../client/config'
import type { SteeringBucket } from '../pages/adventure/prompts'

// --- Types ---

export interface AdventureTurn {
  playerAction: string | null
  narrative: string
  /** Hidden steering roll applied to this turn. Undefined for the opening turn. */
  steering?: SteeringBucket
  /**
   * The deuteragonist's intended action for this turn, generated by an LLM
   * call before the resolution pass. Undefined when the deuteragonist feature
   * is disabled, for the opening turn, or when the partner call failed.
   * Displayed as a chip in the turn UI alongside the player action.
   */
  partnerAction?: string
  /**
   * When the party is split, this holds the deuteragonist's solo narrative
   * for this turn — what happened with them while the protagonist was
   * elsewhere. Undefined when the party is together or no deuteragonist
   * exists. Displayed in a separate tab in the turn UI.
   */
  deuteragonistNarrative?: string
  /**
   * Which phase of a player input produced this turn.
   * - 'resolution' (default): pass 1 — narrates the direct consequences of
   *   `playerAction`. Also used for the opening turn and for legacy turns
   *   saved before the two-pass split.
   * - 'world-step': pass 2 — NPC/world reactions after the resolution.
   *   `playerAction` is always null on these. Runs automatically when the
   *   story's `autoAdvanceWorld` setting is on, or on demand via the
   *   "Advance world" button.
   * - 'continue': an autonomous beat fired by the "Continue story" button.
   *   Like 'world-step' there is no player action, but the WHOLE scene
   *   advances — protagonist, NPCs, and world — on its established
   *   trajectory rather than holding the protagonist still.
   */
  kind?: 'resolution' | 'world-step' | 'continue'
  /**
   * Director brief that drove this turn's prose, when the two-model flow
   * was enabled. Plain markdown — sections like SCENE STATE / BEATS /
   * NPC REACTIONS / ENDING BEAT / DO NOT. Undefined when the director
   * toggle was off, for the opening turn, or when the director call
   * failed and the writer ran un-briefed. Persisted so a drifted turn
   * can be diagnosed against the plan that produced it.
   */
  directorBrief?: string
}

export interface AdventureCompaction {
  summary: string
  generatedAt: string
}

/**
 * The character's standing stance toward the protagonist, on a 7-step scale
 * anchored at the extremes. Replaces the old free-text "status" field —
 * which the analysis model kept padding with redundant scene description
 * (we already have the narrative; we don't need it parroted into the
 * world state).
 *
 * The scale is ordered: index 0 (hatred) is the most negative, index 6
 * (love) the most positive. Movement up or down the ladder should track
 * lasting shifts established by the story, not momentary mood.
 */
export type Disposition =
  | 'hatred'
  | 'hostility'
  | 'distrust'
  | 'indifference'
  | 'warmth'
  | 'devotion'
  | 'love'

export const DISPOSITIONS: ReadonlyArray<Disposition> = [
  'hatred',
  'hostility',
  'distrust',
  'indifference',
  'warmth',
  'devotion',
  'love',
]

/**
 * A single tracked character. Lives in the adventure's living world state
 * and is injected into the narrative prompt so NPCs stay consistent across
 * turns. Phase 1 is fully user-edited; later phases let an analysis model
 * patch these via tool calls.
 */
export interface CharacterCard {
  /** cuid2-style id, generated via generateMessageId() */
  id: string
  /** Canonical name as it should appear in prose */
  name: string
  /**
   * One paragraph describing WHO this character IS — identity, not
   * situation. Appearance, personality, voice, relevant skills,
   * background, defining relationships. Stays true across many scenes;
   * recent events / what-they-just-did belong in the prose, not here.
   */
  description: string
  /** One sentence: what this character currently wants */
  motive: string
  /**
   * Standing stance toward the protagonist on the 7-step scale (hatred →
   * love). This is a *relational* axis, not a momentary mood — what the
   * narrative just showed them doing belongs in the prose, not here.
   */
  disposition: Disposition
  /**
   * When true, the character is off-screen / out of the active story and is
   * NOT injected into the narrative prompt. Kept on the roster for continuity
   * (e.g. they may return later) and to give the analysis model a memory of
   * them. Defaults to false (active).
   */
  archived?: boolean
}

/**
 * A single tracked plot point — something the story has on the books that
 * may yet pay off. Status is a soft lifecycle, not a strict state machine.
 *
 * No `timing` field: the analysis pass runs every turn, so the live state
 * is always up-to-date by definition. Anything time-bound that genuinely
 * lives on its own clock belongs in the world agenda instead.
 */
export interface PlotPoint {
  id: string
  /** Short label, used in lists and as the prompt-side title */
  title: string
  /** One paragraph describing the plot point */
  description: string
  /**
   * - `seeded`: introduced or hinted at, no on-screen progress yet
   * - `active`: currently in motion in the story
   * - `resolving`: paying off this scene / arc
   * - `resolved`: finished; kept for continuity
   * - `abandoned`: explicitly dropped or made impossible (manual UI only —
   *   the analysis pass must call `remove_plot_point` instead, so the
   *   model can't accumulate dead plot points in the world state)
   */
  status: 'seeded' | 'active' | 'resolving' | 'resolved' | 'abandoned'
}

/**
 * A single item on the world's agenda — something that will happen on its
 * own timeline regardless of the protagonist. Drives the world-step pass.
 */
export interface AgendaItem {
  id: string
  /** One sentence: what's about to happen */
  description: string
  /** Soft timing — "in 30 minutes", "at midnight", "next time the bell rings" */
  when: string
}

/**
 * Outcome status for a single analysis tool call.
 * - applied: tool succeeded and modified the world state
 * - noop:    tool succeeded but had nothing to change (already-archived,
 *           identical patch values, etc.)
 * - failed:  tool threw — bad args, unknown id, unknown tool name, etc.
 */
export type AnalysisLogStatus = 'applied' | 'noop' | 'failed'

/**
 * One entry in the analysis activity log. Records a tool call the
 * analysis model requested, the outcome of applying it, and the raw args
 * the model sent — so the user can audit and debug what the model is
 * actually trying to do (including failed and silently-dropped calls).
 *
 * Capped to a small ring buffer in the store.
 *
 * `args`/`status`/`error` are optional only for backward compatibility
 * with previously persisted entries. New entries always set `args` and
 * `status`.
 */
export interface AnalysisLogEntry {
  /** ISO timestamp of when the entry was applied. */
  at: string
  /** Tool name (add_character, patch_plot_point, etc). */
  tool: string
  /** Human-readable summary suitable for the activity log UI. */
  summary: string
  /** The raw arguments the LLM sent for this tool call. */
  args?: unknown
  /** Outcome of the apply attempt. */
  status?: AnalysisLogStatus
  /** Error message when status === 'failed'. */
  error?: string
}

export type AdventurePhase = 'setup' | 'playing'

export interface PersistedState {
  phase: AdventurePhase
  settingInput: string
  protagonistInput: string
  deuteragonistInput?: string
  settingDescription: string
  /** One-time situation used to generate and reconstruct the opening turn. */
  startPrompt?: string
  turns: AdventureTurn[]
  compactions?: Record<string, AdventureCompaction>
  directive?: string
  worldBible?: string
  pendingAction?: string | null
  /**
   * When true, the engine automatically fires the world-step (pass 2)
   * generation after the resolution pass for every player input.
   * Default: false (scene waits for the player; world can still be
   * stepped manually via "Advance world").
   */
  autoAdvanceWorld?: boolean
  /**
   * When true, an extra LLM pass checks each generated narrative for
   * physical/logical inconsistencies and surfaces a warning the user can
   * choose to revise. Default: true. Disabling skips the check entirely
   * (faster turns; useful when the check model is flaky).
   */
  nonsenseCheckEnabled?: boolean
  /**
   * When true, every player action gets a hidden steering roll (well /
   * steady / worse / hell) that biases the protagonist's execution quality
   * for that turn. Default: true. Disabling makes every action resolve at
   * face value — useful when the disaster/friction outcomes feel like they
   * dominate scenes more than the player wants.
   */
  steeringEnabled?: boolean
  /**
   * When true, every turn (resolution AND world-step, except the opening
   * turn) gets an additional "director" LLM pass before the writer call.
   * The director uses the `analysis` category model and produces a short
   * structured plan (beats, NPC reactions, ending beat, things to avoid);
   * the writer then renders that plan as prose. Costs roughly one extra
   * model call per turn — off by default. Useful when the writer model
   * has great prose but loses the plot.
   */
  directorEnabled?: boolean
  /**
   * When true (default), the engine *automates* the living world state in
   * the background: an analysis pass runs after each turn and patches
   * characters / plot points / agenda via tool calls, a synthesis pass
   * rebuilds the model-synthesized storyline, and the resulting state
   * is injected into every writer prompt (`appendLiveWorldState`).
   *
   * When false, all three are skipped — no background LLM calls fire.
   * This governs the automation, not the existence of the cast: the
   * characters below stay editable and still reach every writer prompt,
   * as name + description (`LiveWorldState.characterDetail`), since motive
   * and disposition are fields the analysis pass maintains and are hidden
   * in the UI while it's off. Plot points, the agenda and the synthesized
   * storyline are omitted from prompts entirely — nothing keeps them
   * current. The user can still hand-author a story arc; the
   * storyline-gate continues to run against whatever's in the textarea.
   */
  livingWorldEnabled?: boolean
  /**
   * When true, the storyline-gate brief is held for user accept/reject
   * before the narrative pass that uses it kicks off. Default: false
   * (auto-forward, original behaviour). Useful while iterating on a
   * storyline that's prone to drift — you can veto bad gate output
   * before it pollutes a turn, instead of after.
   */
  gateApprovalEnabled?: boolean
  /**
   * Living world state — characters, plot points, and the world's agenda.
   * Injected into the narrative prompt after the cache breakpoint so the
   * model has a structured, evolving view of who/what is in play.
   *
   * All three are user-editable; a cheap analysis model also patches them
   * via tool calls after each resolution turn while `livingWorldEnabled`
   * is on. `characters` is the exception to that toggle — the cast is
   * always authorable and always injected; see `livingWorldEnabled` above.
   */
  characters?: Record<string, CharacterCard>
  plotPoints?: Record<string, PlotPoint>
  agenda?: AgendaItem[]
  /**
   * Recent analysis-pass updates, oldest first. Capped to a small ring
   * buffer so it doesn't grow unbounded across long adventures.
   */
  analysisLog?: AnalysisLogEntry[]
  /**
   * A model-synthesized global storyline — a few paragraphs describing
   * what is *actually* happening across the story so far, taking the
   * full narrative + all seeded plot points into account. Regenerated
   * by the synthesis pass that runs after each analysis pass, and fed
   * back into the narrative prompt as additional context so the
   * generator has a coherent picture of the larger arc instead of just
   * the fragments visible from individual plot points.
   */
  storyline?: string
  /**
   * When true and a deuteragonist is configured, the party is split —
   * each turn generates two parallel resolution narratives (one for the
   * protagonist, one for the deuteragonist), displayed in tabs. When
   * false (default), only the protagonist narrative is generated and the
   * partner's action is woven into it. Persisted per-adventure.
   */
  partySplit?: boolean
  /**
   * When true, a dedicated per-turn "conditions" pass runs after each
   * turn to maintain a ledger of the physical state of the protagonist
   * and any named characters in the scene (injuries, exhaustion,
   * equipment, position). The ledger is injected into every narrative
   * pass as a reminder so the model can't quietly forget that a
   * character is wounded / unarmed / soaked / etc. Default: false.
   * Independent of `livingWorldEnabled` — works for the protagonist even
   * when the living-world subsystem is off.
   */
  conditionTrackingEnabled?: boolean
  /**
   * When true, the writer prompts carry no paragraph target: the
   * `- N-M paragraphs.` rule is replaced with permission to run as long as
   * the scene needs (`BuildNarrativeOptions.unboundedLength`). Applies to
   * the resolution / world-step / continue / revision passes; the
   * director's beat budget stays bounded. Default: false.
   *
   * The bounded budget (2-4 paragraphs, scaling to 8-10 for a long action)
   * is a ceiling the model obeys even when the action doesn't fit inside
   * it, which makes busy turns read as a cramped summary. Note unbounded
   * turns can hit the model's max-token ceiling and truncate mid-sentence;
   * the token budget is deliberately not raised to compensate.
   */
  unboundedLengthEnabled?: boolean
  /**
   * Model-maintained ledger of physical state for the protagonist +
   * on-page named characters. One concise line per character,
   * protagonist first. Regenerated each turn by the conditions pass;
   * empty until the first pass produces output. User-editable (the
   * World panel exposes it) so a bad entry can be corrected in place.
   */
  conditions?: string
}

// --- localStorage helpers (offline / crash recovery) ---

const STORAGE_KEY = 'adventure-state'

function localLoad(): PersistedState | null {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (!raw) return null
    return JSON.parse(raw) as PersistedState
  } catch {
    return null
  }
}

function localSave(state: PersistedState) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state))
  } catch {
    // localStorage full — silently ignore
  }
}

function localClear() {
  localStorage.removeItem(STORAGE_KEY)
}

/** Save pendingAction to localStorage for crash recovery (backend mode only). */
function savePendingAction(adventureId: string, action: string | null) {
  const key = `adventure-pending-${adventureId}`
  if (action) {
    try {
      localStorage.setItem(key, action)
    } catch { /* ignore */ }
  } else {
    localStorage.removeItem(key)
  }
}

function loadPendingAction(adventureId: string): string | null {
  try {
    return localStorage.getItem(`adventure-pending-${adventureId}`)
  } catch {
    return null
  }
}

function clearPendingAction(adventureId: string) {
  localStorage.removeItem(`adventure-pending-${adventureId}`)
}

// --- Name derivation ---

function deriveNameFromSetting(settingDescription: string): string {
  // Strip PROTAGONIST section if present
  const cleaned = settingDescription.replace(/\n\nPROTAGONIST:[\s\S]*$/, '').trim()
  const firstLine = cleaned.split('\n')[0].trim()
  if (!firstLine) return 'Untitled Adventure'
  if (firstLine.length <= 60) return firstLine
  return `${firstLine.slice(0, 57)}...`
}

// --- Hook ---

export interface AdventurePersistence {
  /** True while loading from backend */
  isLoading: () => boolean
  /** Non-null if loading failed (e.g. 404) */
  loadError: () => string | null
  /** The backend adventure ID (null for offline/new) */
  adventureId: () => string | null
  /** The loaded state (null before load completes, or if new adventure) */
  initialState: () => PersistedState | null
  /** Debounced save (500ms) */
  persistSoon: (state: PersistedState) => void
  /** Immediate save */
  persistNow: (state: PersistedState) => void
  /** Create a new adventure on the backend, returns the new ID */
  createAdventure: (state: PersistedState, name?: string) => Promise<string>
  /** Clear/delete the current adventure state */
  clearState: () => void
  /** Whether we're using backend persistence */
  isBackendMode: boolean
}

export function useAdventurePersistence(routeId: string): AdventurePersistence {
  const isNew = routeId === 'new'
  const isLocal = routeId === 'local'
  // If we have a real adventure ID (not 'new' or 'local'), always attempt backend load
  // regardless of auth state — the API call will fail if not authenticated, which is fine.
  const hasRealId = !isNew && !isLocal
  const isBackendMode = hasRealId || (authStore.isAuthenticated && !authStore.isOfflineMode && !isLocal)

  const [isLoading, setIsLoading] = createSignal(hasRealId || (isBackendMode && !isNew))
  const [loadError, setLoadError] = createSignal<string | null>(null)
  const [adventureId, setAdventureId] = createSignal<string | null>(
    hasRealId ? routeId : null,
  )
  const [initialState, setInitialState] = createSignal<PersistedState | null>(null)

  // Debounce timer
  let debounceTimer: ReturnType<typeof setTimeout> | undefined
  // In-flight PUT tracking
  let saveInFlight = false
  let queuedState: PersistedState | null = null
  // Track the last name we sent to avoid redundant updates
  let lastSentName: string | null = null

  onCleanup(() => {
    clearTimeout(debounceTimer)
  })

  // --- Initial load ---

  if (hasRealId) {
    // Load from backend — always attempt when we have a real ID in the URL
    ;(async () => {
      try {
        const { data, error } = await getMyAdventuresById({ path: { id: routeId } })
        if (error || !data) {
          setLoadError('Adventure not found')
          setIsLoading(false)
          return
        }
        const adventure = data.adventure
        const adventureData = adventure.data as unknown as PersistedState

        // Check for a crashed pendingAction in localStorage
        const pendingAction = loadPendingAction(adventure.id)
        if (pendingAction) {
          adventureData.pendingAction = pendingAction
          clearPendingAction(adventure.id)
        }

        setInitialState(adventureData)
        setIsLoading(false)
      } catch {
        setLoadError('Failed to load adventure')
        setIsLoading(false)
      }
    })()
  } else if (isLocal) {
    // Offline mode: load from localStorage
    setInitialState(localLoad())
  }
  // isNew: initialState stays null (fresh adventure)

  // --- Save logic ---

  /** Strip pendingAction for backend saves (it goes to localStorage instead). */
  function stripPendingAction(state: PersistedState): Omit<PersistedState, 'pendingAction'> {
    const { pendingAction: _, ...rest } = state
    return rest
  }

  async function doBackendSave(state: PersistedState) {
    const id = adventureId()
    if (!id) {
      // Adventure not yet created — queue the save
      queuedState = state
      return
    }

    if (saveInFlight) {
      queuedState = state
      return
    }

    saveInFlight = true

    // Handle pendingAction separately
    savePendingAction(id, state.pendingAction ?? null)

    const cleanState = stripPendingAction(state)

    // Derive name from setting if it changed
    const name = deriveNameFromSetting(state.settingDescription)
    const nameUpdate = name !== lastSentName ? name : undefined
    if (nameUpdate) lastSentName = name

    try {
      await putMyAdventuresById({
        path: { id },
        body: {
          data: cleanState as any,
          ...(nameUpdate ? { name: nameUpdate } : {}),
        },
      })
    } catch (err) {
      console.warn('[adventure-persistence] Save failed:', err)
    } finally {
      saveInFlight = false
      // Flush queued save if there is one
      if (queuedState) {
        const next = queuedState
        queuedState = null
        doBackendSave(next)
      }
    }
  }

  function persistSoon(state: PersistedState) {
    clearTimeout(debounceTimer)
    if (isBackendMode) {
      debounceTimer = setTimeout(() => doBackendSave(state), 500)
    } else {
      debounceTimer = setTimeout(() => localSave(state), 500)
    }
  }

  function persistNow(state: PersistedState) {
    clearTimeout(debounceTimer)
    if (isBackendMode) {
      doBackendSave(state)
    } else {
      localSave(state)
    }
  }

  async function createAdventure(state: PersistedState, name?: string): Promise<string> {
    const adventureName = name || deriveNameFromSetting(state.settingDescription)
    lastSentName = adventureName
    const cleanState = stripPendingAction(state)

    const { data, error } = await postMyAdventures({
      body: {
        name: adventureName,
        data: cleanState as any,
      },
    })

    if (error || !data) {
      throw new Error('Failed to create adventure')
    }

    const newId = data.adventure.id
    setAdventureId(newId)

    // Flush any queued saves now that we have an ID
    if (queuedState) {
      const next = queuedState
      queuedState = null
      doBackendSave(next)
    }

    return newId
  }

  function clearState() {
    if (isBackendMode) {
      const id = adventureId()
      if (id) {
        clearPendingAction(id)
      }
      // Don't delete the adventure from the backend on reset —
      // the user is starting a new one, not destroying the old one
    } else {
      localClear()
    }
  }

  return {
    isLoading,
    loadError,
    adventureId,
    initialState,
    persistSoon,
    persistNow,
    createAdventure,
    clearState,
    isBackendMode,
  }
}
