import { batch } from 'solid-js'
import { createStore, reconcile } from 'solid-js/store'
import type {
  AdventureTurn,
  AdventureCompaction,
  AdventurePhase,
  CharacterCard,
  PlotPoint,
  AgendaItem,
  AnalysisLogEntry,
  PersistedState,
} from '../hooks/useAdventurePersistence'
import { SETTING_KNOBS, type SteeringBucket } from '../pages/adventure/prompts'

// --- State shape ---

interface AdventureState {
  // Core game state
  phase: AdventurePhase
  settingInput: string
  protagonistInput: string
  deuteragonistInput: string
  settingDescription: string
  turns: AdventureTurn[]
  compactions: Record<string, AdventureCompaction>
  directive: string
  worldBible: string
  autoAdvanceWorld: boolean
  nonsenseCheckEnabled: boolean
  steeringEnabled: boolean
  /**
   * When true, every non-opening resolution/world-step turn runs a
   * "director" LLM pass before the writer call. The director (analysis
   * category model) plans the beats; the writer renders them. Off by
   * default. Persisted alongside the other per-adventure toggles.
   */
  directorEnabled: boolean
  /**
   * When false, the engine skips the entire living-world subsystem:
   * the analysis + synthesis background passes don't run, and the
   * characters / plot points / agenda block is NOT injected into any
   * writer prompt. Defaults to true to match prior behaviour. Useful
   * for short or test adventures where the world-tracking overhead
   * isn't worth its cost.
   */
  livingWorldEnabled: boolean

  // Living world state
  characters: Record<string, CharacterCard>
  plotPoints: Record<string, PlotPoint>
  agenda: AgendaItem[]
  /** Activity log of analysis-pass updates (capped ring buffer). */
  analysisLog: AnalysisLogEntry[]
  /** True while the background analysis pass is running. */
  isAnalyzing: boolean
  /**
   * Model-synthesized global storyline — a coherent summary of what is
   * actually happening across the story, regenerated by the synthesis
   * pass after each analysis pass. Empty string until the first synthesis
   * pass produces output.
   */
  storyline: string
  /** True while the background synthesis pass is running. */
  isSynthesizing: boolean
  /**
   * When true, the storyline-gate brief is presented to the user for
   * accept/reject before the narrative pass that consumes it is started.
   * When false (default), the brief is forwarded automatically — same
   * behaviour as before this toggle existed. Persisted alongside other
   * per-story toggles.
   */
  gateApprovalEnabled: boolean
  /**
   * When true and a deuteragonist is configured, the party is separated —
   * each turn generates two parallel narratives (protagonist + deuteragonist).
   * Persisted per-adventure; toggled via the Story panel.
   */
  partySplit: boolean
  /**
   * The brief produced by the storyline-gate pass that is currently
   * awaiting user approval. Null when nothing is pending. Transient — not
   * persisted; if the user navigates away mid-approval, the engine call
   * is rejected and the user picks up from the same pre-narrative state.
   */
  pendingGateBrief: string | null
  /**
   * Which narrative pass the pending brief is gating ('resolution' or
   * 'world-step'). Drives the approval-panel label so the user knows
   * which beat they're approving context for. Null when no brief is
   * pending.
   */
  pendingGateKind: 'resolution' | 'world-step' | null

  // Generation state
  isGenerating: boolean
  streamingContent: string
  /**
   * Which pass is currently streaming into `streamingContent`. The UI
   * uses this to label the streaming block before any chunks arrive
   * (e.g. show the "— the world moves —" chip for a world-step pass).
   * Null when nothing is streaming or the stream is unrelated to a turn
   * (e.g. nonsense-check spinner).
   */
  streamingKind: 'resolution' | 'world-step' | null
  /**
   * Steering bucket already rolled for the resolution pass currently
   * streaming. Rendered as the same chip that appears on the committed
   * turn so the streaming-block → committed-turn swap is a no-op
   * height-wise. Undefined for world-step / no-action streams.
   */
  streamingSteering: SteeringBucket | undefined
  streamingPartnerAction: string | null
  /**
   * Streaming content for the deuteragonist's solo narrative when the
   * party is split. Mirrors `streamingContent` but for the partner's
   * parallel resolution pass. Null when the party is together or no
   * deuteragonist pass is active.
   */
  streamingDeuteragonistContent: string
  pendingAction: string | null
  lastFailedAction: string | null | undefined
  error: string | null

  // Compaction
  compactingKeys: Record<string, boolean>

  // Setting generator
  isGeneratingSetting: boolean
  settingGenFailed: boolean
  knobValues: Record<string, string>
  knobLocks: Record<string, boolean>

  // Nonsense check
  nonsenseWarning: string | null

  // UI state
  playerInput: string
  /** When false, the deuteragonist is inactive this turn (asleep, etc.).
   *  Skips both the partner intent call and any deuteragonist narrative.
   *  Transient — resets to true on every load. */
  deuteragonistActive: boolean
  showStoryPanel: boolean
  showMenu: boolean
  showKnobs: boolean
  scrollLocked: boolean
}

// --- Helpers ---

function defaultKnobValues(): Record<string, string> {
  return Object.fromEntries(SETTING_KNOBS.map((k) => [k.id, '']))
}

function defaultKnobLocks(): Record<string, boolean> {
  return Object.fromEntries(SETTING_KNOBS.map((k) => [k.id, false]))
}

/** Maximum entries kept in the analysis activity log. Older entries are trimmed. */
const ANALYSIS_LOG_MAX = 50

// --- Store ---

const [state, setState] = createStore<AdventureState>({
  phase: 'setup',
  settingInput: '',
  protagonistInput: '',
  deuteragonistInput: '',
  settingDescription: '',
  turns: [],
  compactions: {},
  directive: '',
  worldBible: '',
  autoAdvanceWorld: false,
  nonsenseCheckEnabled: true,
  steeringEnabled: true,
  directorEnabled: false,
  livingWorldEnabled: true,

  characters: {},
  plotPoints: {},
  agenda: [],
  analysisLog: [],
  isAnalyzing: false,
  storyline: '',
  isSynthesizing: false,
  gateApprovalEnabled: false,
  partySplit: false,
  pendingGateBrief: null,
  pendingGateKind: null,

  isGenerating: false,
  streamingContent: '',
  streamingKind: null,
  streamingSteering: undefined,
  streamingPartnerAction: null,
  streamingDeuteragonistContent: '',
  pendingAction: null,
  lastFailedAction: undefined,
  error: null,

  compactingKeys: {},

  isGeneratingSetting: false,
  settingGenFailed: false,
  knobValues: defaultKnobValues(),
  knobLocks: defaultKnobLocks(),

  nonsenseWarning: null,

  playerInput: '',
  deuteragonistActive: true,
  showStoryPanel: false,
  showMenu: false,
  showKnobs: false,
  scrollLocked: true,
})

export const adventureStore = {
  // --- Getters ---

  get phase() {
    return state.phase
  },
  get settingInput() {
    return state.settingInput
  },
  get protagonistInput() {
    return state.protagonistInput
  },
  get deuteragonistInput() {
    return state.deuteragonistInput
  },
  get settingDescription() {
    return state.settingDescription
  },
  get turns() {
    return state.turns
  },
  get compactions() {
    return state.compactions
  },
  get directive() {
    return state.directive
  },
  get worldBible() {
    return state.worldBible
  },
  get autoAdvanceWorld() {
    return state.autoAdvanceWorld
  },
  get nonsenseCheckEnabled() {
    return state.nonsenseCheckEnabled
  },
  get steeringEnabled() {
    return state.steeringEnabled
  },
  get directorEnabled() {
    return state.directorEnabled
  },
  get livingWorldEnabled() {
    return state.livingWorldEnabled
  },
  get characters() {
    return state.characters
  },
  get plotPoints() {
    return state.plotPoints
  },
  get agenda() {
    return state.agenda
  },
  get analysisLog() {
    return state.analysisLog
  },
  get isAnalyzing() {
    return state.isAnalyzing
  },
  get storyline() {
    return state.storyline
  },
  get isSynthesizing() {
    return state.isSynthesizing
  },
  get gateApprovalEnabled() {
    return state.gateApprovalEnabled
  },
  get partySplit() {
    return state.partySplit
  },
  get pendingGateBrief() {
    return state.pendingGateBrief
  },
  get pendingGateKind() {
    return state.pendingGateKind
  },

  get isGenerating() {
    return state.isGenerating
  },
  get streamingContent() {
    return state.streamingContent
  },
  get streamingKind() {
    return state.streamingKind
  },
  get streamingSteering() {
    return state.streamingSteering
  },
  get streamingPartnerAction() {
    return state.streamingPartnerAction
  },
  get streamingDeuteragonistContent() {
    return state.streamingDeuteragonistContent
  },
  get pendingAction() {
    return state.pendingAction
  },
  get lastFailedAction() {
    return state.lastFailedAction
  },
  get error() {
    return state.error
  },

  get compactingKeys() {
    return state.compactingKeys
  },

  isCompacting(key: string): boolean {
    return !!state.compactingKeys[key]
  },

  get isGeneratingSetting() {
    return state.isGeneratingSetting
  },
  get settingGenFailed() {
    return state.settingGenFailed
  },
  get knobValues() {
    return state.knobValues
  },
  get knobLocks() {
    return state.knobLocks
  },

  get nonsenseWarning() {
    return state.nonsenseWarning
  },

  get playerInput() {
    return state.playerInput
  },
  get deuteragonistActive() {
    return state.deuteragonistActive
  },
  get showStoryPanel() {
    return state.showStoryPanel
  },
  get showMenu() {
    return state.showMenu
  },
  get showKnobs() {
    return state.showKnobs
  },
  get scrollLocked() {
    return state.scrollLocked
  },

  // --- Simple setters ---

  setPhase(phase: AdventurePhase) {
    setState('phase', phase)
  },
  setSettingInput(v: string) {
    setState('settingInput', v)
  },
  setProtagonistInput(v: string) {
    setState('protagonistInput', v)
  },
  setDeuteragonistInput(v: string) {
    setState('deuteragonistInput', v)
  },
  setSettingDescription(v: string) {
    setState('settingDescription', v)
  },
  setCompaction(key: string, compaction: AdventureCompaction) {
    setState('compactions', key, compaction)
  },

  setDirective(v: string) {
    setState('directive', v)
  },
  setWorldBible(v: string) {
    setState('worldBible', v)
  },
  setAutoAdvanceWorld(v: boolean) {
    setState('autoAdvanceWorld', v)
  },
  setNonsenseCheckEnabled(v: boolean) {
    setState('nonsenseCheckEnabled', v)
  },
  setSteeringEnabled(v: boolean) {
    setState('steeringEnabled', v)
  },
  setDirectorEnabled(v: boolean) {
    setState('directorEnabled', v)
  },
  setLivingWorldEnabled(v: boolean) {
    setState('livingWorldEnabled', v)
  },

  // --- Living world state CRUD ---

  /** Replace the entire characters map (use for bulk import / reset). */
  setCharacters(v: Record<string, CharacterCard>) {
    setState('characters', reconcile(v))
  },
  /** Insert or fully replace a single character card. */
  upsertCharacter(card: CharacterCard) {
    setState('characters', card.id, card)
  },
  /** Patch fields on an existing character card. No-op if id is unknown. */
  patchCharacter(id: string, patch: Partial<Omit<CharacterCard, 'id'>>) {
    if (!state.characters[id]) return
    setState('characters', id, (prev) => ({ ...prev, ...patch }))
  },
  /** Remove a character entirely. Use archive instead for soft removal. */
  removeCharacter(id: string) {
    setState('characters', id, undefined as unknown as CharacterCard)
  },

  setPlotPoints(v: Record<string, PlotPoint>) {
    setState('plotPoints', reconcile(v))
  },
  upsertPlotPoint(point: PlotPoint) {
    setState('plotPoints', point.id, point)
  },
  patchPlotPoint(id: string, patch: Partial<Omit<PlotPoint, 'id'>>) {
    if (!state.plotPoints[id]) return
    setState('plotPoints', id, (prev) => ({ ...prev, ...patch }))
  },
  removePlotPoint(id: string) {
    setState('plotPoints', id, undefined as unknown as PlotPoint)
  },

  setAgenda(v: AgendaItem[]) {
    setState('agenda', reconcile([...v]))
  },
  upsertAgendaItem(item: AgendaItem) {
    const idx = state.agenda.findIndex((a) => a.id === item.id)
    if (idx >= 0) {
      setState('agenda', idx, item)
    } else {
      setState('agenda', state.agenda.length, item)
    }
  },
  patchAgendaItem(id: string, patch: Partial<Omit<AgendaItem, 'id'>>) {
    const idx = state.agenda.findIndex((a) => a.id === id)
    if (idx < 0) return
    setState('agenda', idx, (prev) => ({ ...prev, ...patch }))
  },
  removeAgendaItem(id: string) {
    setState(
      'agenda',
      reconcile(state.agenda.filter((a) => a.id !== id)),
    )
  },

  /** Append an entry to the analysis activity log; trim oldest if over cap. */
  appendAnalysisLog(entry: AnalysisLogEntry) {
    const next = [...state.analysisLog, entry]
    const trimmed =
      next.length > ANALYSIS_LOG_MAX
        ? next.slice(next.length - ANALYSIS_LOG_MAX)
        : next
    setState('analysisLog', reconcile(trimmed))
  },
  clearAnalysisLog() {
    setState('analysisLog', reconcile([]))
  },
  setIsAnalyzing(v: boolean) {
    setState('isAnalyzing', v)
  },
  setStoryline(v: string) {
    setState('storyline', v)
  },
  setIsSynthesizing(v: boolean) {
    setState('isSynthesizing', v)
  },
  setGateApprovalEnabled(v: boolean) {
    setState('gateApprovalEnabled', v)
  },
  setPartySplit(v: boolean) {
    setState('partySplit', v)
  },
  setPendingGateBrief(brief: string | null, kind: 'resolution' | 'world-step' | null) {
    batch(() => {
      setState('pendingGateBrief', brief)
      setState('pendingGateKind', kind)
    })
  },

  setIsGenerating(v: boolean) {
    setState('isGenerating', v)
  },
  setStreamingContent(v: string) {
    setState('streamingContent', v)
  },
  setStreamingKind(v: 'resolution' | 'world-step' | null) {
    setState('streamingKind', v)
  },
  setStreamingSteering(v: SteeringBucket | undefined) {
    setState('streamingSteering', v)
  },
  setStreamingPartnerAction(v: string | null) {
    setState('streamingPartnerAction', v)
  },
  setStreamingDeuteragonistContent(v: string) {
    setState('streamingDeuteragonistContent', v)
  },
  setPendingAction(v: string | null) {
    setState('pendingAction', v)
  },
  setLastFailedAction(v: string | null | undefined) {
    setState('lastFailedAction', v)
  },
  setError(v: string | null) {
    setState('error', v)
  },

  setCompactingKey(key: string, v: boolean) {
    if (v) {
      setState('compactingKeys', key, true)
    } else {
      setState('compactingKeys', key, undefined as unknown as boolean)
    }
  },

  setIsGeneratingSetting(v: boolean) {
    setState('isGeneratingSetting', v)
  },
  setSettingGenFailed(v: boolean) {
    setState('settingGenFailed', v)
  },
  setKnobValues(v: Record<string, string>) {
    setState('knobValues', reconcile(v))
  },

  setNonsenseWarning(v: string | null) {
    setState('nonsenseWarning', v)
  },

  setPlayerInput(v: string) {
    setState('playerInput', v)
  },
  setDeuteragonistActive(v: boolean) {
    setState('deuteragonistActive', v)
  },
  setShowStoryPanel(v: boolean) {
    setState('showStoryPanel', v)
  },
  setShowMenu(v: boolean) {
    setState('showMenu', v)
  },
  setShowKnobs(v: boolean) {
    setState('showKnobs', v)
  },
  setScrollLocked(v: boolean) {
    setState('scrollLocked', v)
  },

  // --- Complex actions ---

  setKnobValue(knobId: string, value: string) {
    setState('knobValues', knobId, value)
    setState('knobLocks', knobId, true)
  },

  toggleKnobLock(knobId: string) {
    setState('knobLocks', knobId, !state.knobLocks[knobId])
  },

  /** Add a new turn to the story. */
  addTurn(turn: AdventureTurn) {
    setState('turns', state.turns.length, turn)
  },

  /** Replace the entire turns array. */
  setTurns(turns: AdventureTurn[]) {
    setState('turns', reconcile([...turns]))
  },

  /** Update the last turn (e.g. to attach director notes). */
  updateLastTurn(updates: Partial<AdventureTurn>) {
    const idx = state.turns.length - 1
    if (idx >= 0) {
      setState('turns', idx, (prev) => ({ ...prev, ...updates }))
    }
  },

  /** Rewind the story to a specific turn index (inclusive). */
  rewindTo(turnIndex: number) {
    const newCount = turnIndex + 1
    setState('turns', reconcile([...state.turns.slice(0, newCount)]))

    // Invalidate compactions that reference turns beyond the new count
    const cleaned: Record<string, AdventureCompaction> = {}
    for (const [key, comp] of Object.entries(state.compactions)) {
      const end = Number.parseInt(key.split('-')[1], 10)
      if (end < newCount) {
        cleaned[key] = comp
      }
    }
    setState('compactions', reconcile(cleaned))
  },

  /** Remove the last turn and return it. */
  removeLastTurn(): AdventureTurn | undefined {
    const currentTurns = state.turns
    if (currentTurns.length === 0) return undefined
    const removed = currentTurns[currentTurns.length - 1]
    setState('turns', reconcile([...currentTurns.slice(0, -1)]))
    return removed
  },

  /** Build a snapshot suitable for persistence. */
  buildSnapshot(): PersistedState {
    const action = state.pendingAction
    return {
      phase: state.phase,
      settingInput: state.settingInput,
      protagonistInput: state.protagonistInput,
      deuteragonistInput: state.deuteragonistInput || undefined,
      settingDescription: state.settingDescription,
      turns: [...state.turns],
      compactions: { ...state.compactions },
      directive: state.directive,
      worldBible: state.worldBible,
      autoAdvanceWorld: state.autoAdvanceWorld,
      nonsenseCheckEnabled: state.nonsenseCheckEnabled,
      steeringEnabled: state.steeringEnabled,
      directorEnabled: state.directorEnabled,
      livingWorldEnabled: state.livingWorldEnabled,
      gateApprovalEnabled: state.gateApprovalEnabled,
      partySplit: state.partySplit || undefined,
      characters: { ...state.characters },
      plotPoints: { ...state.plotPoints },
      agenda: [...state.agenda],
      analysisLog: [...state.analysisLog],
      storyline: state.storyline,
      ...(action ? { pendingAction: action } : {}),
    }
  },

  /**
   * Batch-finalize a generated turn: clear streaming state and add the turn
   * in a single render frame to avoid content flashing.
   */
  finalizeTurn(turn: AdventureTurn) {
    batch(() => {
      setState('streamingContent', '')
      setState('streamingDeuteragonistContent', '')
      setState('streamingKind', null)
      setState('streamingSteering', undefined)
      setState('streamingPartnerAction', null)
      setState('pendingAction', null)
      setState('isGenerating', false)
      setState('turns', state.turns.length, turn)
    })
  },

  /**
   * Batch-finalize an aborted generation with partial content.
   */
  finalizeAbort(turn: AdventureTurn) {
    batch(() => {
      setState('streamingContent', '')
      setState('streamingDeuteragonistContent', '')
      setState('streamingKind', null)
      setState('streamingSteering', undefined)
      setState('streamingPartnerAction', null)
      setState('pendingAction', null)
      setState('isGenerating', false)
      setState('turns', state.turns.length, turn)
    })
  },

  /** Initialize store from persisted state (or fresh for a new adventure). */
  initialize(saved: PersistedState | null) {
    batch(() => {
      setState({
        phase: saved?.phase ?? 'setup',
        settingInput: saved?.settingInput ?? '',
        protagonistInput: saved?.protagonistInput ?? '',
        deuteragonistInput: saved?.deuteragonistInput ?? '',
        settingDescription: saved?.settingDescription ?? '',
        directive: saved?.directive ?? '',
        worldBible: saved?.worldBible ?? '',
        autoAdvanceWorld: saved?.autoAdvanceWorld ?? false,
        nonsenseCheckEnabled: saved?.nonsenseCheckEnabled ?? true,
        steeringEnabled: saved?.steeringEnabled ?? true,
        directorEnabled: saved?.directorEnabled ?? false,
        livingWorldEnabled: saved?.livingWorldEnabled ?? true,
        gateApprovalEnabled: saved?.gateApprovalEnabled ?? false,
        pendingGateBrief: null,
        pendingGateKind: null,

        isGenerating: false,
        streamingContent: '',
        streamingKind: null,
        streamingSteering: undefined,
        streamingPartnerAction: null,
        streamingDeuteragonistContent: '',
        pendingAction: saved?.pendingAction ?? null,
        lastFailedAction: saved?.pendingAction
          ? saved.pendingAction
          : undefined,
        error: null,

        isGeneratingSetting: false,
        settingGenFailed: false,

        nonsenseWarning: null,

        playerInput: '',
        deuteragonistActive: true,
        showStoryPanel: false,
        showMenu: false,
        showKnobs: false,
        scrollLocked: true,
      })
      // Use reconcile for nested objects/arrays to ensure old keys are cleared
      setState('turns', reconcile(saved?.turns ?? []))
      setState('compactions', reconcile(saved?.compactions ?? {}))
      setState('compactingKeys', reconcile({}))
      setState('knobValues', reconcile(defaultKnobValues()))
      setState('knobLocks', reconcile(defaultKnobLocks()))
      setState('characters', reconcile(saved?.characters ?? {}))
      setState('plotPoints', reconcile(saved?.plotPoints ?? {}))
      setState('agenda', reconcile(saved?.agenda ?? []))
      setState('analysisLog', reconcile(saved?.analysisLog ?? []))
      setState('isAnalyzing', false)
      setState('storyline', saved?.storyline ?? '')
      setState('isSynthesizing', false)
    })
  },

  /** Full reset for starting a new adventure. */
  reset() {
    batch(() => {
      setState({
        phase: 'setup' as const,
        settingInput: '',
        protagonistInput: '',
        deuteragonistInput: '',
        settingDescription: '',
        directive: '',
        worldBible: '',
        autoAdvanceWorld: false,
        nonsenseCheckEnabled: true,
        steeringEnabled: true,
        directorEnabled: false,
        livingWorldEnabled: true,
        gateApprovalEnabled: false,
        pendingGateBrief: null,
        pendingGateKind: null,

        isGenerating: false,
        streamingContent: '',
        streamingKind: null,
        streamingSteering: undefined,
        streamingPartnerAction: null,
        streamingDeuteragonistContent: '',
        pendingAction: null,
        lastFailedAction: undefined,
        error: null,

        isGeneratingSetting: false,
        settingGenFailed: false,

        nonsenseWarning: null,

        playerInput: '',
        deuteragonistActive: true,
        showStoryPanel: false,
        showMenu: false,
        showKnobs: false,
        scrollLocked: true,
      })
      setState('turns', reconcile([]))
      setState('compactions', reconcile({}))
      setState('compactingKeys', reconcile({}))
      setState('knobValues', reconcile(defaultKnobValues()))
      setState('knobLocks', reconcile(defaultKnobLocks()))
      setState('characters', reconcile({}))
      setState('plotPoints', reconcile({}))
      setState('agenda', reconcile([]))
      setState('analysisLog', reconcile([]))
      setState('isAnalyzing', false)
      setState('storyline', '')
      setState('isSynthesizing', false)
    })
  },
}
